In [1]:
import yfinance as yf
import numpy as np
import pandas as pd

In [2]:
data = yf.download("NVDA", start="2021-01-01", end="2026-01-01")

[*********************100%***********************]  1 of 1 completed

In [4]:
data.isna().sum()

Price   Ticker
Close   NVDA      0
High    NVDA      0
Low     NVDA      0
Open    NVDA      0
Volume  NVDA      0
dtype: int64

In [3]:
data

Price            Close        High         Low        Open     Volume
Ticker            NVDA        NVDA        NVDA        NVDA       NVDA
Date
2021-01-04   13.060795   13.597629   12.910402   13.051582  560640000
2021-01-05   13.350873   13.389467   13.034400   13.047099  322760000
2021-01-06   12.563803   13.191769   12.535418   13.169359  580424000
2021-01-07   13.290370   13.323985   12.834709   12.915383  461480000
2021-01-08   13.223390   13.367060   12.989583   13.308796  292528000
...                ...         ...         ...         ...        ...
2025-12-24  188.380234  188.679871  186.362690  187.711052   65528500
2025-12-26  190.297897  192.455270  187.770981  189.688640  139740300
2025-12-29  187.990707  188.530043  185.683524  187.481334  120006100
2025-12-30  187.311539  188.759785  186.702281  188.010698   97687300
2025-12-31  186.272812  190.327864  186.262830  189.339079  120100500

[1255 rows x 5 columns]

In [5]:
df = pd.DataFrame()
df['Volitility'] = np.log(data['High']/data['Low'])
df['Log_Returns'] = np.log(data['Close'] / data['Close'].shift(1))
df['Volume'] = (data['Volume']-data['Volume'].min())/(data['Volume'].max()-data['Volume'].min()) # Min-Max Scale
df['Next_Open'] = (data['Open'].shift(-1) - data['Open'].min()) / (data['Open'].max() - data['Open'].min())

In [6]:
df.dropna(inplace=True)

In [6]:
df

            Volitility  Log_Returns    Volume  Next_Open
Date
2021-01-05    0.026876     0.021967  0.173995   0.011304
2021-01-06    0.051035    -0.060762  0.348283   0.010014
2021-01-07    0.037413     0.056220  0.267828   0.012013
2021-01-08    0.028646    -0.005053  0.153546   0.012297
2021-01-11    0.043815     0.025635  0.306291   0.013986
...                ...          ...       ...        ...
2025-12-23    0.034552     0.029608  0.073963   0.897883
2025-12-24    0.012357    -0.003176  0.000000   0.907928
2025-12-26    0.024641     0.010128  0.050198   0.896716
2025-12-29    0.015214    -0.012198  0.036849   0.899405
2025-12-30    0.010960    -0.003619  0.021753   0.906152

[1253 rows x 4 columns]

In [7]:
df.to_csv("nvidea_stocks.csv")

In [16]:
print(data['Open'].min()) 
print(data['Open'].max())

Ticker
NVDA    10.943877
dtype: float64
Ticker
NVDA    207.814954
dtype: float64