In [17]:
import pandas as pd
from pathlib import Path

In [18]:
df = pd.read_csv(Path().resolve().parent / "data" / "recommendations.csv")

In [19]:
df.sample(3)

,Hair Color,Eye Color,Skin Tone,Under Tone,Torso length,Body Proportion,Recommended Clothing Colors,Avoid Clothing Colors,Recommended Fitting Style,Recommended Materials,Recommended Patterns,Recommended Jewelry Metal,Recommended Shoes,Recommended Clothing Color Wheel Region,Avoid Clothing Color Wheel Region,Fabric Nature,Don't Exaggerate,Do Exaggerate
2880,Black,Light Blue,Olive,Neutral,Short Torso,Oval,"Soft Pinks, Plums, Teal, Neutral Beige","Fluorescents, Harsh Yellow",Wraps and Empire,"Jersey, Knits",Diagonal Lines,Rose Gold,Low Heels or Flats,Neutral-friendly zones (balanced warm/cool lik...,Avoid clashing or harsh contrasts,Stretchy,Don't exaggerate midsection,Exaggerate neckline and legs
3769,Brown,Green,Very Dark,Neutral,Long Torso,Oval,"Soft Pinks, Plums, Teal, Neutral Beige","Fluorescents, Harsh Yellow",Wraps and Empire,"Jersey, Knits",Diagonal Lines,Rose Gold,Heels or Platforms,Neutral-friendly zones (balanced warm/cool lik...,Avoid clashing or harsh contrasts,Stretchy,Don't exaggerate midsection,Exaggerate neckline and legs
11799,Blonde,Light Blue,Fair,Warm,Balanced,Trapezoid,"Earth Tones, Olive, Coral, Peach, Mustard, War...","Cool Blue, Icy Gray, Jewel Tones",Balanced Fit,Soft Blends,Simple Solids,Gold,Any Style,"Warm colors (red, orange, yellow, warm greens)",Opposite on color wheel,Soft,Don't exaggerate any feature,Balance upper and lower body

In [20]:
df.dtypes

Hair Color                                 object
Eye Color                                  object
Skin Tone                                  object
Under Tone                                 object
Torso length                               object
Body Proportion                            object
Recommended Clothing Colors                object
Avoid Clothing Colors                      object
Recommended Fitting Style                  object
Recommended Materials                      object
Recommended Patterns                       object
Recommended Jewelry Metal                  object
Recommended Shoes                          object
Recommended Clothing Color Wheel Region    object
Avoid Clothing Color Wheel Region          object
Fabric Nature                              object
Don't Exaggerate                           object
Do Exaggerate                              object
dtype: object

In [21]:
for col in df.columns:
    print(col + ":")
    print(df[col].unique())
    print("")

Hair Color:
['Black' 'Brown' 'Red' 'Blonde' 'Grey']

Eye Color:
['Brown' 'Green' 'Blue' 'Hazel' 'Grey' 'Black' 'Light Brown' 'Light Blue']

Skin Tone:
['Very Fair' 'Fair' 'Medium' 'Olive' 'Brown' 'Very Dark']

Under Tone:
['Warm' 'Cool' 'Neutral']

Torso length:
['Short Torso' 'Long Torso' 'Balanced']

Body Proportion:
['Rectangle' 'Inverted Triangle' 'Triangle' 'Oval' 'Trapezoid' 'Hourglass'
 'Apple']

Recommended Clothing Colors:
['Earth Tones, Olive, Coral, Peach, Mustard, Warm Red'
 'Jewel Tones, Icy Blue, Lavender, Silver, Emerald'
 'Soft Pinks, Plums, Teal, Neutral Beige']

Avoid Clothing Colors:
['Cool Blue, Icy Gray, Jewel Tones' 'Orange, Mustard, Brown'
 'Fluorescents, Harsh Yellow']

Recommended Fitting Style:
['Defined Waist' 'A-Line Bottoms' 'Emphasize Top' 'Wraps and Empire'
 'Balanced Fit' 'Tailored Fit' 'Empire Waist']

Recommended Materials:
['Structured Cotton' 'Flowy Fabric' 'Lightweight Cotton' 'Jersey, Knits'
 'Soft Blends' 'Stretchy, Soft Fabric' 'Drapey Fabric']

Recommended Patterns:
['Curved Lines' 'Vertical Stripes' 'Bright Tops' 'Diagonal Lines'
 'Simple Solids' 'Subtle Prints' 'Dark Solid Tops']

Recommended Jewelry Metal:
['Gold' 'Silver' 'Rose Gold']

Recommended Shoes:
['Low Heels or Flats' 'Heels or Platforms' 'Any Style']

Recommended Clothing Color Wheel Region:
['Warm colors (red, orange, yellow, warm greens)'
 'Cool colors (blue, green, violet, cool grays)'
 'Neutral-friendly zones (balanced warm/cool like teal, plum, taupe)']

Avoid Clothing Color Wheel Region:
['Opposite on color wheel' 'Avoid clashing or harsh contrasts']

Fabric Nature:
['Firm' 'Flowy' 'Light' 'Stretchy' 'Soft' 'Drapey']

Don't Exaggerate:
["Don't exaggerate straight lines" "Don't exaggerate shoulders"
 "Don't exaggerate hips" "Don't exaggerate midsection"
 "Don't exaggerate any feature" "Don't exaggerate curves excessively"
 "Don't exaggerate waist"]

Do Exaggerate:
['Exaggerate waistline' 'Exaggerate hips' 'Exaggerate upper body'
 'Exaggerate neckline and legs' 'Balance upper and lower body'
 'Highlight waistline' 'Exaggerate shoulders and legs']

# Observations
- This dataset is clearly catered to woman so i need to generalize by dropping woman-only features
- Fabric Nature and materials say the same thing
- 'Avoid Clothing Color Wheel Region' is useless

In [22]:
dfc = df.drop(
    columns=[
        "Fabric Nature",
        "Avoid Clothing Color Wheel Region",
        "Recommended Shoes",
        "Body Proportion",
        "Recommended Fitting Style",
        "Don't Exaggerate",
        "Do Exaggerate",
    ]
)

In [23]:
dfc.columns

Index(['Hair Color', 'Eye Color', 'Skin Tone', 'Under Tone', 'Torso length',
       'Recommended Clothing Colors', 'Avoid Clothing Colors',
       'Recommended Materials', 'Recommended Patterns',
       'Recommended Jewelry Metal', 'Recommended Clothing Color Wheel Region'],
      dtype='object')

In [24]:
for col in dfc.columns:
    print(col + ":")
    print(df[col].unique())
    print("")

Hair Color:
['Black' 'Brown' 'Red' 'Blonde' 'Grey']

Eye Color:
['Brown' 'Green' 'Blue' 'Hazel' 'Grey' 'Black' 'Light Brown' 'Light Blue']

Skin Tone:
['Very Fair' 'Fair' 'Medium' 'Olive' 'Brown' 'Very Dark']

Under Tone:
['Warm' 'Cool' 'Neutral']

Torso length:
['Short Torso' 'Long Torso' 'Balanced']

Recommended Clothing Colors:
['Earth Tones, Olive, Coral, Peach, Mustard, Warm Red'
 'Jewel Tones, Icy Blue, Lavender, Silver, Emerald'
 'Soft Pinks, Plums, Teal, Neutral Beige']

Avoid Clothing Colors:
['Cool Blue, Icy Gray, Jewel Tones' 'Orange, Mustard, Brown'
 'Fluorescents, Harsh Yellow']

Recommended Materials:
['Structured Cotton' 'Flowy Fabric' 'Lightweight Cotton' 'Jersey, Knits'
 'Soft Blends' 'Stretchy, Soft Fabric' 'Drapey Fabric']

Recommended Patterns:
['Curved Lines' 'Vertical Stripes' 'Bright Tops' 'Diagonal Lines'
 'Simple Solids' 'Subtle Prints' 'Dark Solid Tops']

Recommended Jewelry Metal:
['Gold' 'Silver' 'Rose Gold']

Recommended Clothing Color Wheel Region:
['Warm colors (red, orange, yellow, warm greens)'
 'Cool colors (blue, green, violet, cool grays)'
 'Neutral-friendly zones (balanced warm/cool like teal, plum, taupe)']

In [25]:
X = pd.get_dummies(
    dfc[["Hair Color", "Eye Color", "Skin Tone", "Under Tone", "Torso length"]],
    dtype=float,
    drop_first=True,
)

In [26]:
y = pd.get_dummies(
    dfc[
        [
            "Recommended Clothing Colors",
            "Avoid Clothing Colors",
            "Recommended Materials",
            "Recommended Patterns",
            "Recommended Jewelry Metal",
            "Recommended Clothing Color Wheel Region",
        ]
    ],
    dtype=float,
)

In [27]:
X.sample()

,Hair Color_Blonde,Hair Color_Brown,Hair Color_Grey,Hair Color_Red,Eye Color_Blue,Eye Color_Brown,Eye Color_Green,Eye Color_Grey,Eye Color_Hazel,Eye Color_Light Blue,Eye Color_Light Brown,Skin Tone_Fair,Skin Tone_Medium,Skin Tone_Olive,Skin Tone_Very Dark,Skin Tone_Very Fair,Under Tone_Neutral,Under Tone_Warm,Torso length_Long Torso,Torso length_Short Torso
7097,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [28]:
y.sample()

,"Recommended Clothing Colors_Earth Tones, Olive, Coral, Peach, Mustard, Warm Red","Recommended Clothing Colors_Jewel Tones, Icy Blue, Lavender, Silver, Emerald","Recommended Clothing Colors_Soft Pinks, Plums, Teal, Neutral Beige","Avoid Clothing Colors_Cool Blue, Icy Gray, Jewel Tones","Avoid Clothing Colors_Fluorescents, Harsh Yellow","Avoid Clothing Colors_Orange, Mustard, Brown",Recommended Materials_Drapey Fabric,Recommended Materials_Flowy Fabric,"Recommended Materials_Jersey, Knits",Recommended Materials_Lightweight Cotton,...,Recommended Patterns_Diagonal Lines,Recommended Patterns_Simple Solids,Recommended Patterns_Subtle Prints,Recommended Patterns_Vertical Stripes,Recommended Jewelry Metal_Gold,Recommended Jewelry Metal_Rose Gold,Recommended Jewelry Metal_Silver,"Recommended Clothing Color Wheel Region_Cool colors (blue, green, violet, cool grays)","Recommended Clothing Color Wheel Region_Neutral-friendly zones (balanced warm/cool like teal, plum, taupe)","Recommended Clothing Color Wheel Region_Warm colors (red, orange, yellow, warm greens)"
3616,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0